# -*- coding: utf-8 -*-
"""Untitled67-DPA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SomJETMd9mnfw1RaEAQVRyEjLHUWpyPV
"""

#this question will require us to use the priority queue.
#let us import the heap
import heapq
#also the date and time
import datetime

#now we will beig our OOP/class:
#this is where we get the first 8 marks
class Task_class:
  def __init__(self,task_description,date_due,level_of_priority, time_estimated):#what we want our task to store as the question says(these are the parameters in a way)
    #we want to store the below information within the parameters
    self.task_description=task_description
    self.date_due_=date_due
    self.level_of_priority_=level_of_priority
    self.time_estimated_=time_estimated

  #remember a method must be included that has to display the information stores of a user
  #soooo
  def displaying_info(self):
    #now let us return or didplay the information
    return (f'The task is : {self.task_description}\n' #the \n will have the put everything in their own line
             f'The Due Date is: {self.date_due_}\n'
             f'The Priority is as follows: {self.level_of_priority_}\n'
            f'The Estimated Time is: {self.time_estimated_}\n')


  def __str__(self):
    return self.displaying_info()

#now we need to do the the very long class. this is scheduler class
import os
class Task_Scheduler:
  def __init__(self):
    self.task_list=[]#this is an empty list
    #we need to have a standard filename here for simplicity
    self.filename= 'scheduled_tasks.txt'

  def add_task(self,task):#we need use the heapq function here
    heapq.heappush(self.task_list, (task.date_due_, task))
    print(f'The Task {task.task_description} has been added with P:{task.level_of_priority_}\n')

  def next_task(self):#this has to get us the next task
    if self.task_list:
      value_priority, task = heapq.heappop(self.task_list)
      print(f'The next task is:')
      print(task.displaying_info())
      return task
    else:
      return print('TASK NOT AVAILABLE\n')

  #now we want to display the tasks organized
  def task_printing(self):
    #we want sort the tasks by priority
    if not self.task_list:
      return print('No tasks available\n')
    else:
      print('Tasks by priority:\n')
      for level_of_priority, task in sorted(self.task_list):
        print(f'{task}\n')

  def file_save(self, name_of_file): #so we want to write the tasks to a file
    #we want all the tasks to a file that is a text
    with open(name_of_file, 'w') as file:
      file.write('Tasks by priority:\n')
      for level_of_priority, task in sorted(self.task_list):
        file.write(f'{task.task_description}, {task.date_due_} , {task.level_of_priority_}, {task.time_estimated_}\n')
    print(f'Tasks saved to {name_of_file} file\n')

  #we want to able to read waht is written on the file
  def file_read(self, name_of_file):
    try:
      with open(name_of_file, 'r') as file:
        for line in file:
          desc, date_due, level_of_priority, time_estimated = line.strip().split(',')
          task = Task_class(desc, date_due, int(level_of_priority), float(time_estimated))
          self.add_task(task)
      print(f'Tasks loaded from {name_of_file} file\n')
    except FileNotFoundError:
      print(f'File {name_of_file} not found\n')

#now we begin our main menu
def main_menu():
  scheduler = Task_Scheduler() # we need to get a object scheduler

  #we will use a while loop
  while True:
    print('Task Scheduler Menu:')
    print('1. Addition of A Task')
    print('2. Next Task')
    print('3. Display Tasks')
    print('4. Saving A Task to File')
    print('5. Load Tasks from File')
    print('6. Exit')
    print('-----------------------------------')

    #let us give the user an option to enter their input number of what they want from the menu
    decision = input('Enter your choice: ')

    if decision == '1':
      #add the information on the first task
      desc = input('Enter the task description: ')
      date_due = input('Enter the due date (YYYY-MM-DD): ')
      level_of_priority = int(input('Enter the level of priority (1-5): '))
      time_estimated = float(input('Enter the estimated time (hours): '))
      task = Task_class(desc, date_due, level_of_priority, time_estimated)
      scheduler.add_task(task)
    elif decision == '2':
      scheduler.next_task()

    elif decision == '3':
      scheduler.task_printing()

    elif decision == '4':
      name_of_file = input('Enter the name of the file to save tasks: ')
      scheduler.file_save(name_of_file)

    elif decision == '5':
      name_of_file = input('Enter the name of the file to load tasks from: ')
      scheduler.file_read(name_of_file)

    elif decision == '6':
      print('You are exiting the program.')
      break
    else:
      print('Invalid choice. Please try again.\n')

if __name__ == '__main__':
  main_menu()