# -*- coding: utf-8 -*-
"""QUESTION4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HaMGjXQVer1jdcWEGwCXXFYIDODTau37
"""

#import the data and add libraries
import pandas as pd
import numpy as np

#add data---preprocess data
article_data= pd.read_csv('/content/article_headlines (1).csv')
#check for null values
article_data.isnull().sum()
#drop null values
article_data.head() #lets see if it is here?

from matplotlib import pyplot as plt
#lets see the distribtion
_df_0['Label'].plot(kind='hist', bins=20, title='Label')
plt.gca().spines[['top', 'right',]].set_visible(False)

#get the differnces
print(len(article_data)) #number f values available
print(len(article_data[article_data['Label'] == 0])) #number of 0s
print(len(article_data[article_data['Label'] == 1])) #number of 1s

article_data.Headline.unique()

#labels
article_data['Label']= np.asarray(article_data['Label']).astype('float32')

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(article_data['Headline'], article_data['Label'], test_size=0.2)

import re
#normalize by removing things we dont wang
def normalize(data):
  normalized = []
  for i in data:
    i = i.lower()
    #no urls
    i = re.sub('https?://\S+|www\.\S+', '', i)
    #no html
    i = re.sub(' +', '', i)
    i = re.sub('^', '', i)
    i = re.sub('$', ' ', i)
    i= re.sub('\n', '', i)
    i = re.sub('\\W' , ' ', i)
    #no punctuation
    normalized.append(i)
  return normalized


x_train = normalize(x_train)
x_test = normalize(x_test)

!pip install tensorflow
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

#tokenize and pad texts data
T = Tokenizer(num_words=5000) # oov_token='<OOV>')
T.fit_on_texts(article_data['Headline'])
word_index = T.word_index
seq = T.texts_to_sequences(article_data['Headline'])
padded = pad_sequences(seq, maxlen=20, padding='post') # truncating='post')

#labels
labs= np.asarray(article_data['Label']).astype('float32')

#train-split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(padded, labs, random_state=42,  test_size=0.2)

# Corrected the typo 'Droput' to 'Dropout'
from tensorflow.keras.layers import Embedding, Dense, Flatten, Dropout #GlobalAveragePooling1D
from tensorflow.keras.models import Sequential


article_model = Sequential([
    Embedding(10000,128), Flatten(), Dropout(0.5), Dense(24, activation='relu'), Dense(1, activation='sigmoid')
])

article_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
article_model.build(input_shape=(None, 20))
article_model.summary()

#train model
article_model.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test), verbose=2)
y_predict = (article_model.predict(X_test) > 0.5).astype('int32')

#import the evaulations (acc and precision)
from sklearn.metrics import accuracy_score, precision_score
accuracy_score(y_test, y_predict)
precision_score(y_test, y_predict)

print('Accuracy score: ', accuracy_score(y_test, y_predict))
print('Precision score: ', precision_score(y_test, y_predict))
#article_data['Label'].value_counts()