# -*- coding: utf-8 -*-
"""Untitled67_Question2-dpa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hS7mU8w6OP-AsSuFkG7fRoiTByP05vFH
"""

!pip install networkx matplotlib

#importing the neccesary libraries
import networkx as nx
import matplotlib.pyplot as plt

#now we begin our class
class ManagerConnection:
  def __init__(self):
    self.graph = nx.Graph() #this ensures that an undirected graph is created

  def add_connection(self, node):
    if node in self.graph.nodes:
      print(f"Node {node} already exists in the graph.")
    else:
      self.graph.add_node(node)
      print(f'Node {node} has been added to the graph.')


  def connect_nodes(self, node1, node2):
    if node1 not in self.graph.nodes or node2 not in self.graph.nodes:
      print(" User must exist before connection is created.")
    elif node1 == node2:
      print("Nodes cannot be connected to themselves.")
    else:
      self.graph.add_edge(node1, node2)
      print(f'Connection between {node1} and {node2} has been established.')


  def displaying_users(self):
    #we want to see all the nodes present within the network
    if len(self.graph.nodes)==0:
      print('Network has no users yet')
    else:
      print('Users in the network are:')
      for node in self.graph.nodes:
        print(node)

  def connections_views(self):
    if len(self.graph.edges())==0:
      print('Network has no connections yet')
    else:
          print('Connections in the network are:')
          for n1, n2 in self.graph.edges:
            print(f'{n1} <> {n2}')

  def display_graph_(self):
  #we want to see the network
    if len(self.graph.nodes())==0:
      print('Network has no users yet')
      return
    plt.figure(figsize=(8,8))
    nx.draw(self.graph, with_labels=True, node_color='deeppink', edge_color='gray', font_weight= 'bold')
    plt.title(' Social Network Graph')
    plt.show()

def main():
  tuv = ManagerConnection()

  while True:
    print('\n SOCIAL MENU')
    print('1.Add user')
    print('2. Addition in Connection')
    print('3. View All users')
    print('4. View connections')
    print('5. Display Graph')
    print('6. Exit')

    try:
      DECISION = int(input('Enter your choice according to the menu: '))
      if DECISION == 1:
        node=input('Enter the username: ').strip()
        tuv.add_connection(node)
      elif DECISION == 2:
        node1=input('Enter the first username: ').strip()
        node2=input('Enter the second username: ').strip()
        tuv.connect_nodes(node1, node2)
      elif DECISION == 3:
        tuv.displaying_users()
      elif DECISION == 4:
        tuv.connections_views()
      elif DECISION == 5:
        tuv.display_graph_()

      elif DECISION == 6:
        print('Exiting the program')
        break
      else:
        print('Invalid choice')
    except ValueError:
      print("Invalid input. Please enter a number from the menu.")

if __name__ == '__main__':
  main()