# -*- coding: utf-8 -*-
"""UPDATED-QUESTION4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fx6siDQG0txcZe-YAzot979bI_au0Vyo
"""

#import for the dataset
import pandas as pd
import numpy as np
# Read the CSV file with the correct delimiter
data = pd.read_csv('/content/customer_segmentation.csv', delimiter=';')
#DROP all customer like question stated as it serves no purpose in here
data = data.drop(['customer_id','age', 'visits_per_month'], axis=1)
# remove any values that are missing
print(data.head())
print(data.isnull().sum())
data = data.dropna()
print(data.head())

#do we need to convert anything?
data.info()

#create an empty list for the for-loop

import matplotlib.pyplot as plt
import seaborn as sns
#now the scatter plot
plt.figure(figsize=(13, 9))
sns.scatterplot(x='income', y='spending_score', data=data, color = 'deeppink')
plt.xlabel('Income') #X-AXIS
plt.ylabel('Score of Spending') #Y-AXIS
plt.title('Customer Segmentation Graph') #TITLE OF GRAPH
plt.grid(True)
plt.show()

from sklearn.preprocessing import StandardScaler
#standardize data
x= StandardScaler() #assign the scaler library to a variable
data_scaled = x.fit_transform(data) #fiit the data

#lets add the Kmeans
from sklearn.cluster import KMeans


WCSS = []
for t in range(1, 11):
    kmeans = KMeans(n_clusters=t, random_state=42)
    kmeans.fit(data_scaled)
    WCSS.append(kmeans.inertia_)

#now plot
plt.figure(figsize=(13,9))
plt.plot(range(1, 11), WCSS, marker='o', linestyle='--', color='deeppink')
plt.title('The Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')
plt.grid(True)
plt.show()

kmeans_final = KMeans(n_clusters=5, random_state=42)
#assign the  avaribale for the clustered data
data['Cluster'] = kmeans_final.fit_predict(data_scaled)
#visualize this:
data.head()

!pip install kneed
from kneed import KneeLocator
z= KneeLocator(range(1, 11), WCSS, curve='convex', direction='decreasing')
otimal_cluster = z.elbow
print(f"The Clusters' optimal number is as follows: {otimal_cluster}")

kmeans= KMeans(n_clusters=otimal_cluster, init='k-means++', random_state=42)
CLUSTER= kmeans.fit_predict(data_scaled)

data['cluster'] = CLUSTER

#PLOT THE CLUSTERS
plt.figure(figsize=(13,9))
sns.scatterplot(x='income', y='spending_score', hue='cluster', data=data, palette=sns.color_palette('husl',4), s=100, alpha=0.8)

#add the centriods
centroids = x.inverse_transform(kmeans.cluster_centers_)
plt.scatter(centroids[:, 0], centroids[:, 1], marker= 'X', s=250, alpha=0.8, c='hotpink', label='Centroids', edgecolor='red', linewidth=2)
plt.xlabel('Income')
plt.ylabel('Score of Spending')
plt.title(f'Customer Segmentation Graph (k=4)')
plt.legend()
plt.grid(True, alpha=0.5)
plt.show()

print(data.groupby('Cluster').mean())