# -*- coding: utf-8 -*-
"""Untitled65-QUESTION4-MLA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mq3pbSUYKZg-pLf_rzBctBeCxsKoOSt9
"""

# Wine clustering
#add in the dataset into the code
import pandas as pd

dataframe = pd.read_csv('/content/wine_clustering.csv')
dataframe #to display that it is inserted

#there no need to encode, delete identifiers
#so we standardize data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler() #intialize the library
scaler_wine=scaler.fit(dataframe) #add the dataset to be standarzied

from sklearn.cluster import KMeans
#add the K-means with optimal of 4
optimnal_value = 4
kmeans = KMeans(n_clusters=optimnal_value, random_state=42, n_init=10)
# Apply the scaler to the dataframe and then fit the KMeans model
clusters=kmeans.fit_predict(scaler_wine.transform(dataframe))
#add the cluster label to the intial data
dataframe['Cluster'] = clusters

wcss = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42, max_iter=300, n_init=10)
    # Remove the 'Cluster' column before transforming the dataframe
    kmeans.fit(scaler_wine.transform(dataframe.drop('Cluster', axis=1)))
    wcss.append(kmeans.inertia_)

plt.figure(figsize=(10,10))
plt.plot(range(1, 11), wcss, marker='o', linestyle='--')
plt.title('Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')
plt.xticks(range(1, 11))
plt.grid(True)
plt.show()

#now we use PCA for full dimensionality
#also the graph
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
pca= PCA(n_components=2)

# Apply the scaler before adding the cluster column
scaled_dataframe = scaler_wine.transform(dataframe.drop('Cluster', axis=1))

principal_components = pca.fit_transform(scaled_dataframe)
pca_dataframe = pd.DataFrame(data=principal_components, columns=['PC1', 'PC2'])
pca_dataframe['Cluster'] = clusters

#now we plot
plt.figure(figsize=(10, 10))
scatter = plt.scatter(pca_dataframe['PC1'], pca_dataframe['PC2'], c=pca_dataframe['Cluster'], cmap='viridis', s=50, )
plt.xlabel('Principal Component 1'. format(pca.explained_variance_ratio_[0]* 100))
plt.ylabel('Principal Component 2'. format(pca.explained_variance_ratio_[1]* 100))
plt.legend(*scatter.legend_elements(), title='Cluster')
plt.title('Wine Clustering with PCA')
plt.grid(True)
plt.show()