# -*- coding: utf-8 -*-
"""Question1.MLA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g-Gkq1rrcsEWhoQ1JKSJSb_jvKKCcnli
"""

#import the neccesary libaries to insert the execel file and to clean the data
import pandas as pd
import numpy as np
#assign the dataset to a dataframe
dataframe = pd.read_csv('/content/dementia.csv')
#let print the the dataset to see if our data has been inserted and what it actually looks like
dataframe

#let us get the information, to chcek for missing values etc.
dataframe.info()

#now we remove missing values
dataframe.dropna(inplace=True)
print(f"The row count after: {dataframe.shape[0]}")
#now we check sum of the number of missings values of each feature
print('\nVerification of the sum in missing values:')
print(dataframe.isnull().sum())

"""## Separating Features and Target"""

#separate the identifier and target from the x-features given
X = dataframe.drop(["PatientID", "DoctorInCharge",'Diagnosis', 'Unnamed: 0'], axis=1)
Y = dataframe["Diagnosis"]

numerical_columns = X.select_dtypes(include=[np.number]).columns.tolist()
catergorical_features = X.select_dtypes(exclude=[np.number]).columns.tolist()

#display the first few rows of X and Y
print("Features (X):")
display(X)
print("\nTarget (Y):")
display(Y.head())

Y

dataframe.info()

import sklearn
from sklearn.preprocessing import OneHotEncoder
#assign the non-numerical/catergorical columns to a list
catergory_columns = ['Forgetfulness' , 'Smoking', 'EducationLevel', 'Ethnicity', 'Gender']
#the one-hot encoding is the techenique that i know that will be better to convert the objects into numericals, its better for ctergorical data instead
#pandas were already imported so we can use the "get_dummies" ,library.
#since the columns with catergorical data is inserted to a list:
X_encoded = pd.get_dummies(X, drop_first=True, dtype=int) #always add the type of data you want it to be converted to!!!!
print(X_encoded.head())#this will show that the encoding was applied.

#the scaler
from sklearn.preprocessing import StandardScaler
s = StandardScaler() #asssign the libary to variable =initialize

#identify the continuous columns for scaling-floats and integers that were given tp us INTIALLY/Beginning of the dataset before converting catergory columns to binary!! NOT BINARY OR CATERGORICAL(0/1 features). Ope the excel file and identify continous columns
continous_columns = ['BMI' , 'AlcoholConsumption','PhysicalActivity', 'DietQuality', 'SleepQuality',  'ADL' , 'Age', 'CholesterolLDL', 'CholesterolHDL', 'CholesterolTotal', 'CholesterolTriglycerides', 'MMSE', 'FunctionalAssessment', 'SystolicBP', 'DiastolicBP']
#put these features that are comtinuous in a list/array so we can only scale them-NOT THE BINARY COLUMNS!!
#let us transform the numerical columns that they have a standard deviation of 1 and 0 as the mean
x_scaled = s.fit_transform(X_encoded[continous_columns]) # Apply scaler to the selected columns of X_encoded
X_scaled = pd.DataFrame(x_scaled, columns=continous_columns, index=X_encoded.index) #data that was scaled is converted back to the dataframe and maintain index
#show the data scaled
X_scaled.head()

#let us if it it scaled in terms mean and deviation
print('\nThe Means of the Scaled Data:')
print(X_scaled.mean())
print('\nThe Standard Deviations of the Scaled Data:')
print(X_scaled.std())

#now we need to add/merge these scaled and continous features.
X_final_look = X_encoded.copy()
X_final_look[continous_columns] = X_scaled
print(X_final_look.shape)
X_final_look.head()

#now let us slipt the data- this line helps us to not intialize the y over and over again when we need to build our models
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_final_look, Y, test_size=0.2, random_state=42)

#import the libaries needed.
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE, SelectKBest, f_classif
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print('--- a) SelectKBest ---')
#intialize the Selector of SelectKBest
select_K_B = SelectKBest(score_func=f_classif, k=12)
select_K_B.fit(X_train, Y_train)
#get the names of selected features
selected_mask_kbest = select_K_B.get_support()
selected_columns_kbest = X_train.columns[selected_mask_kbest].tolist()
print("Selected Features(k=12):", selected_columns_kbest)

print('---b) Logistic Regression---')
#we need to select the RFE's estimator
rfe_estimator= LogisticRegression(solver='liblinear', penalty='l1', random_state=42)
#intialize RFE
rfe = RFE(estimator=rfe_estimator, n_features_to_select=12)
rfe.fit(X_train, Y_train)
selected_mask_rfe = rfe.get_support()
selected_columns_rfe = X_train.columns[selected_mask_rfe].tolist()
print("Selected Features(RFE):", selected_columns_rfe)

#take the above features of each and the target "Diagnosis" and build a logistic regression
print("== Logistic Regression of the SelectKBest: ")

#train the features of the selectKbest selected
X_train_kbest = X_train[selected_columns_kbest]
X_test_kbest = X_test[selected_columns_kbest]
#train the model
model_kbest = LogisticRegression(max_iter=1000, random_state=42)
model_kbest.fit(X_train_kbest, Y_train)
#prediction solving
y_pred_kbest = model_kbest.predict(X_test_kbest)
#evaluate the perfomance of the model
accuracy_kbest = accuracy_score(Y_test, y_pred_kbest)
print("Accuracy:", accuracy_kbest)
print("Classification Report:\n", classification_report(Y_test, y_pred_kbest))
print('\nConfusion Matrix" \n)', confusion_matrix(Y_test, y_pred_kbest))

print("== Logistic Regression of the RFE: ")

#train the features of the RFE selected
X_train_rfe = X_train[selected_columns_rfe]
X_test_rfe = X_test[selected_columns_rfe]
#train the model
model_rfe = LogisticRegression(max_iter=1000, random_state=42)
model_rfe.fit(X_train_rfe, Y_train)
#print model
print(model_rfe)
#prediction solving
y_pred_rfe = model_rfe.predict(X_test_rfe)
#evaluate the perfomance of the model
accuracy_rfe = accuracy_score(Y_test, y_pred_rfe)
print("Accuracy:", accuracy_rfe)
print("Classification Report:\n", classification_report(Y_test, y_pred_rfe))
print('\nConfusion Matrix" \n)', confusion_matrix(Y_test, y_pred_rfe))

"""**DECISION TREE**"""

#build the decision tree for the SelectKBest then for the RFE as well using data we used above
#add the library for decision tree
from sklearn.tree import DecisionTreeClassifier

#add the label that states decision tree
print('===Decision Tree for the SelectKBest :')
#get the features selected for this method above and train and test them
X_train_kbest = X_train[selected_columns_kbest]
X_test_kbest = X_test[selected_columns_kbest]
#intialize the Decsision tree then train and test it
model_kbest = DecisionTreeClassifier(random_state=42)
model_kbest.fit(X_train_kbest, Y_train)
#print the model
print(model_kbest)
#prediction solving
y_pred_kbest = model_kbest.predict(X_test_kbest)
#evaluate the perfomance of the model
accuracy_kbest = accuracy_score(Y_test, y_pred_kbest)
print("Accuracy:", accuracy_kbest)
print("Classification Report:\n", classification_report(Y_test, y_pred_kbest))
print('\nConfusion Matrix" \n)', confusion_matrix(Y_test, y_pred_kbest))

# build the decision for the RFE
print('===Decision Tree for the RFE :')
#train and test the columns we got from rfe
X_train_rfe = X_train[selected_columns_rfe]
X_test_rfe = X_test[selected_columns_rfe]
#intialize the Decsision tree then train and test it
tree_rfe = DecisionTreeClassifier(random_state=42)
tree_rfe.fit(X_train_rfe, Y_train)
#prediction solving
y_pred_rfe = tree_rfe.predict(X_test_rfe)
#evalute the model to see how well it is doing
accuracy_rfe = accuracy_score(Y_test, y_pred_rfe)
print("Accuracy:", accuracy_rfe)
print("Classification Report:\n", classification_report(Y_test, y_pred_rfe))
print('\nConfusion Matrix" \n)', confusion_matrix(Y_test, y_pred_rfe))