# -*- coding: utf-8 -*-
"""Untitled79.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MUYkAT6aAaqtYnFCQbMjooWfkaGGGymA
"""

#we are doing a huffman code
import heapq
class BinaryTreeNode:
    def __init__(self,value,freq):
        self.value=value
        self.freq=freq
        self.left=None
        self.right=None

    #value = char

    def __lt__(self,other):
        return self.freq<other.freq

  #now our huffman begins
class HuffmanCoding:
  def build_frequency_dict(self,data):
    freq_dict={}
    for char in data:
      if char not in freq_dict:
        freq_dict[char]=1
      freq_dict[char]+=1
    return freq_dict

  #next method
  def build_huffman_tree(self, freq_dict):
    #heap must created
    heap = []
    for char, freq in freq_dict.items():
      heapq.heappush(heap, BinaryTreeNode(char, freq))
      #now we do the while loop
      while len(heap) > 1:
        #pop/remove the smallest 2
        left_child = heapq.heappop(heap)
        right_child = heapq.heappop(heap)

        #now we want a parent node with frequnce
        parent = BinaryTreeNode(None, left_child.freq + right_child.freq)
        parent.left = left_child
        parent.right = right_child

        heapq.heappush(heap, parent)
      return heap[0]

rhaenyra