# -*- coding: utf-8 -*-
"""Untitled59.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tOSEYv7qdTo3vVheWavEL01WpStNZW2I
"""

#we need to build a logistic model :
#import pandas
import pandas as pd
import numpy as np
#add in the the dataset
dataframe = pd.read_csv('/content/loan_status.csv')
#display it
dataframe

#the info(datatypes) is given to us in the scenario
#separate x and y
X = dataframe.drop('loan_status', axis=1)
y = dataframe['loan_status']

X
y

#now encoding
import sklearn
from sklearn.preprocessing import OneHotEncoder
#assign non-numerical features into a list
categorical_features = ['person_gender', 'person_education', 'person_home_ownership', 'loan_intent', 'home_ownership', 'previous_loan_defaults_on_file']
X_encoded = pd.get_dummies(X, drop_first=True, dtype=int)
X_encoded

#let us do the same for y
y_encoded = pd.get_dummies(y, drop_first=True, dtype=int)
y_encoded

#we need to scale
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
#continous columns
continous_columns = ['person_age', 'person_income','loan_amnt', 'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length']
x_scaled = scaler.fit_transform(X_encoded[continous_columns])
X_scaled= pd.DataFrame(x_scaled, columns=continous_columns, index=X_encoded.index)
X_scaled

X_final_look = X_encoded.copy() #this adds what we did in the abpve as our new x
X_final_look[continous_columns] = X_scaled

X_final_look
#y as well
Y_final_look = y_encoded.copy()
#now we split data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final_look, Y_final_look, test_size=0.2, random_state=42)

#now we import libraries
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.metrics import accuracy_score, classification_report

#intialzie the seletKBest
select_K_B= SelectKBest(score_func=f_classif, k=10)
select_K_B.fit(X_train, y_train)

#get the features
selected_features = select_K_B.get_support()
selected_features = X_train.columns[selected_features].tolist()
selected_features

model = LogisticRegression()
model.fit(X_train, y_train)

#evalution
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print("Classification Report:\n", classification_rep)

