# -*- coding: utf-8 -*-
"""Untitled66-QUESTION3-MLA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GCxmA9OKfg3vT9vLukOdyQL1X_OMR4R1
"""

#UBER EATS QUESTION ABOUT GRADIENT DESCENT:
#let us insert the dataset into this code
import pandas as pd

#assign/ intialize :
dataframe = pd.read_csv("/content/uber_eats.csv")
#display
dataframe

dataframe=dataframe.drop('Order_ID', axis=1)
dataframe

#let us check for missing values
print('\nThe values that are missing are: ', dataframe.isnull().sum())

#now we gonna do a loop that will fill these empty values ups
for column in dataframe.columns:
  if dataframe[column].dtype == 'object':
    dataframe[column].fillna(dataframe[column].mode()[0], inplace=True)
  else:
    dataframe[column].fillna(dataframe[column].mean(), inplace=True)

print('n\After Null vlaues replacement: ', dataframe.isnull().sum())

from sklearn.preprocessing import OneHotEncoder

#assign the catergorical columns:
columns_to_encode = ['Vehicle_Type', 'Time_of_Day', 'Traffic_Level', 'Weather']

#assign the encoder
encoder_data = OneHotEncoder(drop='first', sparse_output=False)

#fit and transform the data
encoded_data_final = encoder_data.fit_transform(dataframe[columns_to_encode])

#now we convert the df with column
encoded_df = pd.DataFrame(encoded_data_final, columns=encoder_data.get_feature_names_out(columns_to_encode))

dataframe = pd.concat([dataframe.drop(columns_to_encode, axis=1), encoded_df], axis=1)

print(dataframe)

#separate the x and y after the encoding
X= dataframe.drop('Delivery_Time_min', axis=1)
Y= dataframe['Delivery_Time_min']
print(X) #after encoding, cleaning anddropping unneccesary

#selecting the selectmethod
from sklearn.feature_selection import SelectKBest, f_regression
selector = SelectKBest(score_func=f_regression, k=8)
X_selected = selector.fit_transform(X, Y)
selected_features = X.columns[selector.get_support()]
print('\nFeatures that have selected via the SELECTKBest: ', selected_features)

#standardize
from sklearn.preprocessing import StandardScaler
s_X = StandardScaler()
X_scaled = s_X.fit_transform(X_selected) # Apply scaler to the selected features
s_y = StandardScaler()
y_scaled = s_y.fit_transform(Y.values.reshape(-1, 1)).flatten() # Apply scaler to the target variable

print ('\n Standard Deviation: ', X_scaled.std())
print ('\n Mean: ', X_scaled.mean())
print(X_scaled[:5]) # Display the first 5 rows of the scaled NumPy array

import numpy as np
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_scaled, test_size=0.2, random_state=42)

#convert to our numpy arrays
X_train_np = np.c_[np.ones(X_train.shape[0]), X_train]
y_training_np = y_train.reshape(-1, 1)
#intialzie the parametres that will be used
learning_rate = 0.01
num_iterations = 1000
theta = np.zeros((X_train_np.shape[1], 1))
n=len(y_training_np)

#now we loop the gradient descent
for v in range(num_iterations):
  hypothesis = X_train_np.dot(theta)
  loss = hypothesis - y_training_np
  gradient = X_train_np.T.dot(loss) * (1/n)
  theta -= learning_rate * gradient

#let us print the parametres
print(theta.flatten())

import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))
plt.scatter(X_train[:, 0], y_train, color='blue', label= 'Actual Data')
plt.plot(X_train[:, 0],X_train_np.dot(theta), color= 'green', label= 'label Line ' ) #line f regression of gradient descent
plt.xlabel('Feature')
plt.ylabel('Target')
plt.title('Linear Regression with Gradient Descent')
plt.legend()
plt.show()

#evaluate the model performance
from sklearn.metrics import mean_squared_error, r2_score


#prepare to test data with bias term
X_test_np = np.c_[np.ones(X_test.shape[0]), X_test]
y_test_np = y_test.reshape(-1, 1)

#make predictions on the test data
y_pred = X_test_np.dot(theta)
mse = mean_squared_error(y_test_np, y_pred)
r2 = r2_score(y_test_np, y_pred)
rmse = np.sqrt(mse)


print("Mean Squared Error:", mse)
print("Root Mean Squared Error:", rmse)
print("R-squared:", r2)
#print mae
print("Mean Absolute Error:", np.mean(np.abs(y_pred - y_test_np)))