# -*- coding: utf-8 -*-
"""Untitled53-1d.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17FgjLYr9jh86VM7RndMkAdFy80DIoOIi
"""

#question 1d
#import the neccersary library
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency

#create a table of the observed data as a table(rows=weekdat and weekend)
#the value are the total number of deliveries that took place
data_of_deliveries= np.array([[110, 80], [68, 135]])
#now we neeed to add the observed data to a data frame hence pd was used
data= pd.DataFrame(data_of_deliveries, columns=['WESTERN CAPE', 'GAUTENG'], index=['During The Week', 'During The Weekend'])
#print the data frame
print("The delivery counts that were taken are as follows: ")
print(data)

#now the test to take place
chi2, p_value, dof, expected= chi2_contingency(data_of_deliveries)
#print the results from the tests that took place
print(f'P-Value is : {p_value:.4f}') #this is the p value rounded off 4 places
print(f'Chi-Sqauare Stats is as follows: {chi2:.2f}')
print("/nFrequencies Expected only if there is no difference: ")
print(expected)

