# -*- coding: utf-8 -*-
"""Untitled53-1c-.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M-EM-B8bjnuNI5yVLnAFoWRN0JK0UUpq
"""

#import the necesaary libraries
import pandas as pd
import numpy as np
import statsmodels.api as sm
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.stats.outliers_influence import variance_inflation_factor

#reproducible results with numpy
np.random.seed(42)
#get a balanced synthetic data
number_of_days = 210
#the provinces
province = ['Gauteng', 'WesternCape']
#now the days of the week
days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
#now the dataframe
deliveries_df = pd.DataFrame({"Day_Of_Week": [day for week in range(number_of_days//7) for day in days], "Province": np.random.choice(province, size=number_of_days), 'Holiday': np.random.choice([0,1], size=number_of_days, p=[0.85, 0.15])})
#generate deliveries
deliveries = 40

#effect of the feature
effects_of_days= {'Monday': 0, 'Tuesday': 2, 'Wednesday': 3, 'Thursday': 1, 'Friday': 5, 'Saturday': -3, 'Sunday': -5}
effects_of_provinces = {'Gauteng': 0, 'WesternCape': 5}

deliveries_df['DELIVERIES']= [deliveries + effects_of_days[row['Day_Of_Week']] + effects_of_provinces[row['Province']] + (-8 if row['Holiday']==1 else 0) + np.random.normal(0, 3) for _, row in deliveries_df.iterrows()]
deliveries_df['DELIVERIES'] = deliveries_df['DELIVERIES'].round().clip(lower=0)
deliveries_df.head()
#fit model
deliver_model = smf.ols(formula='DELIVERIES ~ C(Day_Of_Week) + C(Province) + Holiday', data=deliveries_df).fit()
print(deliver_model.summary())

def deliveries_data():
  return deliveries_df

j = pd.get_dummies(data=deliveries_df[['Day_Of_Week','Holiday',  'Province']], drop_first=True)
j=sm.add_constant(j)
# Convert boolean columns to integers
for col in j.columns:
    if j[col].dtype == 'bool':
        j[col] = j[col].astype(int)
vif = [variance_inflation_factor(j.values, i) for i in range(j.shape[1])]
print('\nVIF per variable: ')
for col, v in zip(j.columns, vif):
    print(f'{col}: {v:.2f}')

sm.qqplot(deliver_model.resid, line='s')
plt.title('Quantile-Quantile plot')
plt.show()