# -*- coding: utf-8 -*-
"""QUESTION3-AIA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uTvmF3gQgHsEKvkip59-Gwj7ysnLXPJR
"""

#a) import the neccessary
import pandas as pd
import numpy as np

flood_dataset = pd.read_csv('/content/flood_dataset (1).csv')
flood_dataset.head() #see if it is inserted

#get the info of each
flood_dataset.info() #to check if everything is numbers

#we wanna test data
from sklearn.model_selection import train_test_split

#drop the target from the x-values
x = flood_dataset.drop('Flood Risk (1=Yes, 0=No)', axis=1)
y = flood_dataset['Flood Risk (1=Yes, 0=No)']

#now the training and test set
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42, stratify=y)

#standardize to scale the dataset for it to be distributed well
from sklearn.preprocessing import StandardScaler
z = StandardScaler()
x_train = z.fit_transform(x_train)
x_test = z.transform(x_test)

#now let us build the model as data has been split and so forth
from tensorflow.keras.models import Sequential
# Import the Dense and Dropout layers
from tensorflow.keras.layers import Dense, Dropout

flood_model = Sequential([Dense(64, activation='relu', input_shape=(x_train.shape[1],)), Dense(32, activation='relu'), Dropout(0.3), Dense(1)]) #, activation='sigmoid')])

s= {0:1, 1:2}

from tensorflow.keras.optimizers import Adam
flood_model.compile(optimizer=Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy', 'Precision'])

from tensorflow.keras.callbacks import EarlyStopping
k = EarlyStopping(monitor='val_precision', patience=10, mode= 'max', restore_best_weights=True)
#train the model
# Changed validation_data to validation_split to use a percentage of the training data for validation
flood_model.fit(x_train, y_train, epochs=10, batch_size=16, validation_split=0.2 , callbacks =k , class_weight=s, verbose=1)

#ow evaluation
from sklearn.metrics import precision_score , classification_report
y_pred_proba = flood_model.predict(x_test)
#threshold = np.percentile(y_pred_proba, 100 * (1 - y_test.mean()))
y_pred_high_precision = (y_pred_proba > 0.7).astype(int)
#calculate precision
precision = precision_score(y_test, y_pred)
print(f'Precision: {precision:.3f}')

print('\Classification report is as follows: ')
print(classification_report(y_test, y_pred_high_precision))

#ow evaluation
from sklearn.metrics import precision_score , classification_report
y_pred_proba = flood_model.predict(x_test)
#threshold = np.percentile(y_pred_proba, 100 * (1 - y_test.mean()))
y_pred_high_precision = (y_pred_proba > 0.7).astype(int)
#calculate precision
# Changed y_pred_proba to y_pred_high_precision to pass binary predictions to precision_score
precision = precision_score(y_test, y_pred_high_precision)
print(f'Precision: {precision:.3f}')

print('\Classification report is as follows: ')
print(classification_report(y_test, y_pred_high_precision))

