# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GLR8gY0AFuwtQmI3WzqLCT39xntysd9q
"""

import pandas as pd
#placing the datasets upon the the file path
df= pd.read_csv(r'C:\Users\Thula\OneDrive\Documents\Desktop\ITSCA-ASSIGNMENT-EDUV49633 Books_Data.csv')
df

import pandas as pd
import numpy as np
#placing in the dataset give wiithin the question:
file = "/content/Books_Data.csv"
try:
  df = pd.read_csv(file ,sep=";")
except Exception as e:
  print(f"The file {e} cannot be read")
  raise

#the first thing instructions wants to check the dimension of the dataset
print(df.shape)
print("The above represents the dimension of the dataset as rows and columns")



#I need to use the standard naming convention for all COLUMNs(camelCases or _)
df.columns = [column_name.strip().lower().replace(' ', '_') for column_name in df.columns]
print("The column names are as follows: " , df.columns) #to print the output of the naming conversion done in the above line

#Now No NULLS!! must be present
print("The values that are null in each column;\n", df.isnull().sum())

df = df.fillna({
    'author_rating': 'Beginner', #default for the author rating
    'genre': 'Fiction', #default
    'gross_sales' : df['gross_sales'].mean(), #place missing gross_sales with mean
    'publishing_revenue' : 0
})

df = df.replace([np.inf, -np.inf], np.nan)
df = df.dropna()
#Years colums must conTAIN nO DECIMALS!!!! or any value that is wrong.
#It will first convert the column of Year of float to an int as it will remove the decimals
try:
  df["publishing_year"] = df["publishing_year"].astype(float)
  df = df[df["publishing_year"].notna()]
  df["publishing_year"] = df["publishing_year"].astype(int)
  #now filter out the invalid years
  years_invalid = df[~df["publishing_year"].between(1000, 2100)]
  df = df[df["publishing_year"] .between(1000,2100)] #get rid of the -300/ 380 as a year with the correct range

  #if not years_invalid.empty:
    #print(f"Years that are invalid that are removed:\n" , years_invalid[['book_name' ,'publishing_year']])
except Exception as e:
  print(f"ERROR FOR: {e}")

#use a function to simplify the rating process
#from beginner, intermediate and expert
def author_ratings(rate_of_author):
  rate_of_author = str(rate_of_author).lower() if pd.notna(rate_of_author) else ''
  beginner_rate = ["beginner" , "low" , "1" ,"2"  "novice"]
  intermediate_rate = ["intermediate", "medium", "3", "4", "5"]
  expert_rate = ["expert", "6", "7", "8" , "high"]

  if rate_of_author in beginner_rate:
    return "Beginner"
  elif rate_of_author in intermediate_rate:
    return "Intermediate"
  elif rate_of_author in expert_rate:
    return "Expert"
  else:
    #print(f"Not recognized: {rate_of_author}")
    return "Beginner"


df["author_rating"] = df["author_rating"].apply(author_ratings)

#print(df["author_rating"].value_counts())
#genre also simplified.

type_of_genre = {"fiction", "non-fiction", "children"}
#need to normalize the lower cases
df["genre"] = df["genre"].str.lower().str.strip()
#this is the tranformation
df["genre"] = df["genre"].apply(lambda x: x.capitalize() if x in type_of_genre else "Fiction")
#print(df["genre"].value_counts())
#The operation costs must be calculated using the given formula
df["operating_cost"] = df["gross_sales"] - df["publisher_revenue"]



if 'gross_sales' in df.columns and 'publisher_revenue' in df.columns:
    df['operating_cost'] = df['gross_sales'] - df['publisher_revenue']
else:
    print("Columns 'gross_sales' or 'publisher_revenue' not found in the DataFrame.")

#now 8th patr of the instructions requires us compute the average book rating for each
#publisher, and the x^, Q2 and standard devationin gross sales
each_publiser_average = df.groupby("publisher")["book_ratings_count"].mean() #call the functions
gross_sale_mean = df["gross_sales"].mean()
median_of_gross_sale = df["gross_sales"].median()
gross_sale_standard_deviation = df["gross_sales"].std()

print(f"The Standard Deviation of the Gross Sale is: {gross_sale_standard_deviation}")
print(f"The Median of the Gross Sale is: {median_of_gross_sale}")
print(f"The Mean of the Gross Sale is: {gross_sale_mean}")

#they will be displayed

#ensure that the "sale rank" column is rempve from the dataset
df = df.drop(columns=["sales_rank"])

#create the dataset of the top 10 book
top_10_books = df[df["book_average_rating"] >= 4].nlargest(10, "book_average_rating")[["book_name" , "author_rating" , "book_average_rating"]]

#save it!!
df.to_csv("cleaned_books_data.csv", index=False)
top_10_books.to_csv("top_10_books.csv", index=False)

print("\nTop 10 Books with the rating of 4 and above") #just to see if it is actually there
print(top_10_books[["book_name" , "book_average_rating"]])
print("The data has been cleaned, with everything needed and saved")