# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18CqitNzbUdN3rpkvBhvxCvc5fTB6da0m
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
#insert in the cleaned dataset
file = "/content/cleaned_books_data.csv"
df = pd.read_csv(file)
#df the file is inserted
#lets insert a style for the graphs
sns.set(style="darkgrid")

#now to start perform the report:
#top books:
#print(df.columns)
top_10_books = df.sort_values(by='book_average_rating', ascending=False) #what is go by

plt.figure(figsize=(11, 7))
sns.barplot(x='book_average_rating', y='book_name', data=top_10_books.head(10)) #thenames must be same as in set
plt.title('Top 10 Books by Rating')
plt.xlabel('Rating Of Books')
plt.ylabel('Book Title of each')
plt.show

plt.figure(figsize=(11, 7))
sns.barplot(data= df, x='genre', y='gross_sales', palette= "Set2", estimator=sum)
plt.title('Sales Distribution Across Genre')
plt.xlabel('Genre')
plt.ylabel("Gross Sales")
plt.xticks(rotation=45)
plt.show()

#convert to the correct format
df["publishing_year"] = pd.to_datetime(df["publishing_year"].astype(str), format= "%Y", errors="coerce")

df = df.dropna(subset=["publishing_year"])
#now the fiction books ONLY but be filtered
books_that_fiction = df[df["genre"] == "Fiction"]

sales_in_fiction_over_time = books_that_fiction.groupby("publishing_year")["gross_sales"].sum().reset_index()
plt.figure(figsize=(11, 7))
sns.lineplot(data=sales_in_fiction_over_time, x="publishing_year", y="gross_sales" , marker="o", color="b")
plt.title("Sales in Distribution in Fiction Books Over Time") #the title of graph
plt.xlabel("Published Years") #title of x
plt.ylabel("Total Gross Sales") #title of y
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(13, 7))
#what the data is about, x, y and type of graph
sns.barplot(data=df, x="publisher" , y="gross_sales", palette="Set1", estimator=sum)
plt.title("Distribution Of Sales Across Various Publsihers")
plt.xlabel("Publishers Found:")
plt.ylabel("Total Gross Sales")
plt.xticks(rotation=45, ha="right")
plt.show()

#now for the top publisher
#finding the publisher:
biggest_publisher_of_all_time = df.groupby("publisher")["gross_sales"].sum().idxmax()

#filter from the top publisher
biggest_published_books = df[df["publisher"] == biggest_publisher_of_all_time]

#the genre
sales_from_genre = biggest_published_books.groupby("genre")["gross_sales"].sum().reset_index()

plt.figure(figsize=(12,7))
sns.barplot(data=sales_from_genre, x="genre" , y="gross_sales", palette="coolwarm")
plt.title(f"{biggest_publisher_of_all_time} 's Genre Sales")
plt.xlabel("Genre")
plt.ylabel("Total Gross Sales")
plt.xticks(rotation=45)
plt.show()

#relations btwn book ratings and sales
plt.figure(figsize=(12,7))
sns.scatterplot(data=df, x="book_average_rating", y="gross_sales", alpha=0.7)
plt.title("Relationship Between Book Ratings and Sales")
plt.xlabel("Average Book Rates")
plt.ylabel("Total Gross Sales")
plt.show()

#book rating between book rating counts and gross sales
plt.figure(figsize=(12,7))
sns.scatterplot(data=df, x="book_ratings_count", y="gross_sales", alpha=0.7)
plt.title("Relationship Between Book Ratings Count and Sales")
plt.xlabel("Book Ratings Count")
plt.ylabel("Total Gross Sales")
plt.show()

plt.figure(figsize=(12,7))
sns.scatterplot(data=df, x="book_average_rating", y="author_rating", alpha=0.7)
plt.title("Relationship Between Book Ratings and Author Ratings")
plt.xlabel("Average Book Rates")
plt.ylabel("Ratings Of Authors")
plt.show()

#now using book rate count
plt.figure(figsize=(12,7))
sns.scatterplot(data=df, x="book_ratings_count", y="author_rating", alpha=0.7)
plt.title("Relationship Between Book Ratings Count and Author Ratings")
plt.xlabel
plt.ylabel("Ratings Of Authors")
plt.show()