# -*- coding: utf-8 -*-
"""Untitled36.ipynb-QUESTION3-ITSCA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11WN1GoNaUuyjxtepDezU0gR9RM8w0yYo
"""

import pandas as pd
import requests
from bs4 import BeautifulSoup
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

#prompt user to input job title
name_of_job = input("Enter the name of the job that you seek for: ").strip()
search_term = name_of_job.lower().replace(' ' , '-')
#get link
url = f'https://www.careerjunction.co.za/jobs/{search_term}'

print(f'Fetching results from: {url}')

#retry setup
retry_strategy = Retry(total=3, backoff_factor=1, status_forcelist=[429, 500, 502, 503, 504])
adapter = HTTPAdapter(max_retries=retry_strategy)
http = requests.Session()
http.mount("https://", adapter)
http.mount("http://", adapter)

#make request
try:
   response= http.get(url, headers={'User-Agent' : 'Mozilla/5.0 (Winows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36'} ,timeout=30)
   response.raise_for_status()

   # Move the code that uses 'response' inside the try block
   soup = BeautifulSoup(response.content, 'html.parser')

   #get the job cards
   title_of_job =soup.find_all('a', attrs={'jobid' : True})
   overviews = soup.find_all('ul', class_='job-overview')

   print(f'found{len(title_of_job)} job titles and {len(overviews)} overviews')
   jobs_list = []
   for x in range(min(len(title_of_job), len(overviews))):
     # Check if the current job title element has an 'href' attribute
     if 'href' in title_of_job[x].attrs:
       title = title_of_job[x].text.strip()
       link = 'https://www.careerjunction.co.za' + title_of_job[x]['href']
       overview = overviews[x]

       salary= overview.find('li' , class_='salary')
       position = overview.find('li' , class_= 'position')
       location = overview.find('li' , class_='location')
       posted = overview.find('li' , class_='updated-time')

        #adding to list
       jobs_list.append({
         'Title' : title,
         'Recruiter' : 'N/A',
         'Salary' : salary.text.strip() if salary else 'N/A',
         'position' : position.text.strip() if position else 'N/A',
         'location' : location.text.strip() if location else 'N/A',
         'posted_date' : posted.text.strip() if posted else 'N/A'
       })
     else:
         # Optionally, print a message or log that a job title was skipped due to no href
         print(f"Skipping a job title element because it has no 'href' attribute: {title_of_job[x]}")
#creating the new dataframe for each result found
   data = pd.DataFrame(jobs_list)
   Filename = f'{search_term}_job-results.csv'
   data.to_csv(Filename, index= False)
   print(f'Successfully scraped {len(data)} jobs. Results saved to {Filename}')
   print ('\nSample of scraped data: ')
   print(data.head())

#This handles the errors
except requests.exceptions.RequestException as e:
   print(f'Error fetching data: {e}')
   exit()

